baseURL = "/"
languageCode = "en-us"
title = "intend"
disableKinds = ["taxonomy", "term", "rss", "sitemap", "robotstxt"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
